### ISSUE TITLE
G1 Old duration is empty at source

### ISSUE THREAD

**Issue by sedulam** [oleg-glushak/cassandra-prometheus-jmx#4]
Something seems to be wrong with the G1 old generation duration metric. These are instant metrics from a cluster using G1. Although it gives the time for the young generation, the old is always zero.
```
jvm_gc_collection_seconds_count{gc="G1 Young Generation",} 13707.0
jvm_gc_collection_seconds_sum{gc="G1 Young Generation",} 2193.606
jvm_gc_collection_seconds_count{gc="G1 Old Generation",} 0.0
jvm_gc_collection_seconds_sum{gc="G1 Old Generation",} 0.0
```

**Comment by VictorBHub** [comment]
@sedulam please check this [answer](https://stackoverflow.com/a/53846765).
it seems like you want it to stay on 0 always, otherwise, it might imply a problem.

**Comment by sedulam** [comment]
@VictorBHub ah yes, I saw that post some time ago and dropped this issue. The problem seems to reside on the way that JMX exposes these metrics. The way it uses for CMS can't really be reused properly for G1. Fortunately, there is already a ticket for open JDK to change how G1 metrics are exported: https://bugs.openjdk.java.net/browse/JDK-8196989

I'm closing this issue.

**Comment by revolyw** [comment]
Is this issue still being followed up?
